chore: add back github actor and OTP

diff --git a/.github/workflows/publish-release.yml b/.github/workflows/publish-release.yml
--- a/.github/workflows/publish-release.yml
+++ b/.github/workflows/publish-release.yml
@@ -34,6 +34,12 @@ jobs:
           fetch-depth: 0
           token: ${{ secrets.GITHUB_TOKEN }}
 
+      - if: ${{ github.event.pull_request.merged != true && contains('["ghiscoding"]', github.actor) != true }}
+        name: Exit early when current actor is not allowed to push new release
+        run: |
+          echo "Error: Your GitHub username (${{ github.actor }}) is not on the allowed list of admins for this workflow"
+          exit 1
+
       - name: Set NodeJS
         uses: actions/setup-node@v4
         with:
@@ -60,13 +66,35 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
+      - name: Debug Authentication
+        run: |
+          echo "Checking npm registry"
+          npm config get registry
+          echo "Checking npm user"
+          git config --global user.name "${{ github.actor }}"
+          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
+          npm whoami || echo "Authentication failed"
+
       - name: 🧪 Dry-Run - GitHub Release
         if: ${{ inputs.dryrun == true }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NPM_CONFIG_PROVENANCE: true
         run: |
+          git config --global user.name "${{ github.actor }}"
+          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
+          npm whoami
           npx release-it --ci --dry-run --npm.skipChecks=true
+
+      - name: OTP
+        if: ${{ inputs.dryrun != true }}
+        uses: step-security/wait-for-secrets@v1
+        id: wait-for-secrets
+        with:
+          secrets: |
+            OTP:
+              name: 'OTP to publish package'
+              description: 'OTP from authenticator app'
 
       - name: Fixed Version Release ⚙️ / NPM Publish 📦
         if: ${{ inputs.version != '' }}
@@ -74,7 +102,10 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NPM_CONFIG_PROVENANCE: true
         run: |
-          npx release-it ${{ inputs.version }} --ci --npm.skipChecks=true --plugins.'@release-it/conventional-changelog'.ignoreRecommendedBump=false
+          git config --global user.name "${{ github.actor }}"
+          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
+          npm whoami
+          npx release-it ${{ inputs.version }} --ci --npm.skipChecks=true --plugins.'@release-it/conventional-changelog'.ignoreRecommendedBump=false --npm.otp=${{ steps.wait-for-secrets.outputs.OTP }}
 
       - name: GitHub Release 🏷️ / NPM Publish 📦
         if: ${{ inputs.dryrun != true && inputs.version == '' }}
@@ -82,4 +113,7 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NPM_CONFIG_PROVENANCE: true
         run: |
-          npx release-it --ci --npm.skipChecks=true
+          git config --global user.name "${{ github.actor }}"
+          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
+          npm whoami
+          npx release-it --ci --npm.skipChecks=true --npm.otp=${{ steps.wait-for-secrets.outputs.OTP }}
