fix: publish with OIDC

diff --git a/.github/workflows/publish-release.yml b/.github/workflows/publish-release.yml
--- a/.github/workflows/publish-release.yml
+++ b/.github/workflows/publish-release.yml
@@ -66,10 +66,17 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
+      - name: Debug Authentication
+        run: |
+          echo "Checking npm registry"
+          npm config get registry
+          echo "Checking npm user"
+          npm whoami || echo "Authentication failed"
+
+
       - name: 🧪 Dry-Run - GitHub Release
         if: ${{ inputs.dryrun == true }}
         env:
-          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NPM_CONFIG_PROVENANCE: true
         run: |
